package model

type OffSet struct {
	Timestamp  int        `json:"timestamp"`
	Signatures Signatures `json:"signatures"`
	Netvars    Netvars    `json:"netvars"`
}

type Signatures struct {
	AnimOverlays                   uint `json:"anim_overlays"`
	ClientstateChokedCommands      uint `json:"clientstate_choked_commands"`
	ClientstateDeltaTicks          uint `json:"clientstate_delta_ticks"`
	ClientstateLastOutgoingCommand uint `json:"clientstate_last_outgoing_command"`
	ClientstateNetChannel          uint `json:"clientstate_net_channel"`
	ConvarNameHashTable            uint `json:"convar_name_hash_table"`
	DwClientState                  uint `json:"dwClientState"`
	DwClientStateGetLocalPlayer    uint `json:"dwClientState_GetLocalPlayer"`
	DwClientStateIsHLTV            uint `json:"dwClientState_IsHLTV"`
	DwClientStateMap               uint `json:"dwClientState_Map"`
	DwClientStateMapDirectory      uint `json:"dwClientState_MapDirectory"`
	DwClientStateMaxPlayer         uint `json:"dwClientState_MaxPlayer"`
	DwClientStatePlayerInfo        uint `json:"dwClientState_PlayerInfo"`
	DwClientStateState             uint `json:"dwClientState_State"`
	DwClientStateViewAngles        uint `json:"dwClientState_ViewAngles"`
	DwEntityList                   uint `json:"dwEntityList"`
	DwForceAttack                  uint `json:"dwForceAttack"`
	DwForceAttack2                 uint `json:"dwForceAttack2"`
	DwForceBackward                uint `json:"dwForceBackward"`
	DwForceForward                 uint `json:"dwForceForward"`
	DwForceJump                    uint `json:"dwForceJump"`
	DwForceLeft                    uint `json:"dwForceLeft"`
	DwForceRight                   uint `json:"dwForceRight"`
	DwGameDir                      uint `json:"dwGameDir"`
	DwGameRulesProxy               uint `json:"dwGameRulesProxy"`
	DwGetAllClasses                uint `json:"dwGetAllClasses"`
	DwGlobalVars                   uint `json:"dwGlobalVars"`
	DwGlowObjectManager            uint `json:"dwGlowObjectManager"`
	DwInput                        uint `json:"dwInput"`
	DwInterfaceLinkList            uint `json:"dwInterfaceLinkList"`
	DwLocalPlayer                  uint `json:"dwLocalPlayer"`
	DwMouseEnable                  uint `json:"dwMouseEnable"`
	DwMouseEnablePtr               uint `json:"dwMouseEnablePtr"`
	DwPlayerResource               uint `json:"dwPlayerResource"`
	DwRadarBase                    uint `json:"dwRadarBase"`
	DwSensitivity                  uint `json:"dwSensitivity"`
	DwSensitivityPtr               uint `json:"dwSensitivityPtr"`
	DwSetClanTag                   uint `json:"dwSetClanTag"`
	DwViewMatrix                   uint `json:"dwViewMatrix"`
	DwWeaponTable                  uint `json:"dwWeaponTable"`
	DwWeaponTableIndex             uint `json:"dwWeaponTableIndex"`
	DwYawPtr                       uint `json:"dwYawPtr"`
	DwZoomSensitivityRatioPtr      uint `json:"dwZoomSensitivityRatioPtr"`
	DwbSendPackets                 uint `json:"dwbSendPackets"`
	DwppDirect3DDevice9            uint `json:"dwppDirect3DDevice9"`
	FindHudElement                 uint `json:"find_hud_element"`
	ForceUpdateSpectatorGlow       uint `json:"force_update_spectator_glow"`
	InterfaceEngineCvar            uint `json:"interface_engine_cvar"`
	IsC4Owner                      uint `json:"is_c4_owner"`
	MBDormant                      uint `json:"m_bDormant"`
	MBIsLocalPlayer                uint `json:"m_bIsLocalPlayer"`
	MFlSpawnTime                   uint `json:"m_flSpawnTime"`
	MPStudioHdr                    uint `json:"m_pStudioHdr"`
	MPitchClassPtr                 uint `json:"m_pitchClassPtr"`
	MYawClassPtr                   uint `json:"m_yawClassPtr"`
	ModelAmbientMin                uint `json:"model_ambient_min"`
	SetAbsAngles                   uint `json:"set_abs_angles"`
	SetAbsOrigin                   uint `json:"set_abs_origin"`
}

type Netvars struct {
	CsGamerulesData                uint `json:"cs_gamerules_data"`
	MArmorValue                    uint `json:"m_ArmorValue"`
	MCollision                     uint `json:"m_Collision"`
	MCollisionGroup                uint `json:"m_CollisionGroup"`
	MLocal                         uint `json:"m_Local"`
	MMoveType                      uint `json:"m_MoveType"`
	MOriginalOwnerXuidHigh         uint `json:"m_OriginalOwnerXuidHigh"`
	MOriginalOwnerXuidLow          uint `json:"m_OriginalOwnerXuidLow"`
	MSurvivalGameRuleDecisionTypes uint `json:"m_SurvivalGameRuleDecisionTypes"`
	MSurvivalRules                 uint `json:"m_SurvivalRules"`
	MAimPunchAngle                 uint `json:"m_aimPunchAngle"`
	MAimPunchAngleVel              uint `json:"m_aimPunchAngleVel"`
	MAngEyeAnglesX                 uint `json:"m_angEyeAnglesX"`
	MAngEyeAnglesY                 uint `json:"m_angEyeAnglesY"`
	MBBombDefused                  uint `json:"m_bBombDefused"`
	MBBombPlanted                  uint `json:"m_bBombPlanted"`
	MBBombTicking                  uint `json:"m_bBombTicking"`
	MBFreezePeriod                 uint `json:"m_bFreezePeriod"`
	MBGunGameImmunity              uint `json:"m_bGunGameImmunity"`
	MBHasDefuser                   uint `json:"m_bHasDefuser"`
	MBHasHelmet                    uint `json:"m_bHasHelmet"`
	MBInReload                     uint `json:"m_bInReload"`
	MBIsDefusing                   uint `json:"m_bIsDefusing"`
	MBIsQueuedMatchmaking          uint `json:"m_bIsQueuedMatchmaking"`
	MBIsScoped                     uint `json:"m_bIsScoped"`
	MBIsValveDS                    uint `json:"m_bIsValveDS"`
	MBSpotted                      uint `json:"m_bSpotted"`
	MBSpottedByMask                uint `json:"m_bSpottedByMask"`
	MBStartedArming                uint `json:"m_bStartedArming"`
	MBUseCustomAutoExposureMax     uint `json:"m_bUseCustomAutoExposureMax"`
	MBUseCustomAutoExposureMin     uint `json:"m_bUseCustomAutoExposureMin"`
	MBUseCustomBloomScale          uint `json:"m_bUseCustomBloomScale"`
	MClrRender                     uint `json:"m_clrRender"`
	MDwBoneMatrix                  uint `json:"m_dwBoneMatrix"`
	MFAccuracyPenalty              uint `json:"m_fAccuracyPenalty"`
	MFFlags                        uint `json:"m_fFlags"`
	MFlC4Blow                      uint `json:"m_flC4Blow"`
	MFlCustomAutoExposureMax       uint `json:"m_flCustomAutoExposureMax"`
	MFlCustomAutoExposureMin       uint `json:"m_flCustomAutoExposureMin"`
	MFlCustomBloomScale            uint `json:"m_flCustomBloomScale"`
	MFlDefuseCountDown             uint `json:"m_flDefuseCountDown"`
	MFlDefuseLength                uint `json:"m_flDefuseLength"`
	MFlFallbackWear                uint `json:"m_flFallbackWear"`
	MFlFlashDuration               uint `json:"m_flFlashDuration"`
	MFlFlashMaxAlpha               uint `json:"m_flFlashMaxAlpha"`
	MFlLastBoneSetupTime           uint `json:"m_flLastBoneSetupTime"`
	MFlLowerBodyYawTarget          uint `json:"m_flLowerBodyYawTarget"`
	MFlNextAttack                  uint `json:"m_flNextAttack"`
	MFlNextPrimaryAttack           uint `json:"m_flNextPrimaryAttack"`
	MFlSimulationTime              uint `json:"m_flSimulationTime"`
	MFlTimerLength                 uint `json:"m_flTimerLength"`
	MHActiveWeapon                 uint `json:"m_hActiveWeapon"`
	MHBombDefuser                  uint `json:"m_hBombDefuser"`
	MHMyWeapons                    uint `json:"m_hMyWeapons"`
	MHObserverTarget               uint `json:"m_hObserverTarget"`
	MHOwner                        uint `json:"m_hOwner"`
	MHOwnerEntity                  uint `json:"m_hOwnerEntity"`
	MHViewModel                    uint `json:"m_hViewModel"`
	MIAccountID                    uint `json:"m_iAccountID"`
	MIClip1                        uint `json:"m_iClip1"`
	MICompetitiveRanking           uint `json:"m_iCompetitiveRanking"`
	MICompetitiveWins              uint `json:"m_iCompetitiveWins"`
	MICrosshairId                  uint `json:"m_iCrosshairId"`
	MIDefaultFOV                   uint `json:"m_iDefaultFOV"`
	MIEntityQuality                uint `json:"m_iEntityQuality"`
	MIFOV                          uint `json:"m_iFOV"`
	MIFOVStart                     uint `json:"m_iFOVStart"`
	MIGlowIndex                    uint `json:"m_iGlowIndex"`
	MIHealth                       uint `json:"m_iHealth"`
	MIItemDefinitionIndex          uint `json:"m_iItemDefinitionIndex"`
	MIItemIDHigh                   uint `json:"m_iItemIDHigh"`
	MIMostRecentModelBoneCounter   uint `json:"m_iMostRecentModelBoneCounter"`
	MIObserverMode                 uint `json:"m_iObserverMode"`
	MIShotsFired                   uint `json:"m_iShotsFired"`
	MIState                        uint `json:"m_iState"`
	MITeamNum                      uint `json:"m_iTeamNum"`
	MLifeState                     uint `json:"m_lifeState"`
	MNBombSite                     uint `json:"m_nBombSite"`
	MNFallbackPaintKit             uint `json:"m_nFallbackPaintKit"`
	MNFallbackSeed                 uint `json:"m_nFallbackSeed"`
	MNFallbackStatTrak             uint `json:"m_nFallbackStatTrak"`
	MNForceBone                    uint `json:"m_nForceBone"`
	MNModelIndex                   uint `json:"m_nModelIndex"`
	MNTickBase                     uint `json:"m_nTickBase"`
	MNViewModelIndex               uint `json:"m_nViewModelIndex"`
	MRgflCoordinateFrame           uint `json:"m_rgflCoordinateFrame"`
	MSzCustomName                  uint `json:"m_szCustomName"`
	MSzLastPlaceName               uint `json:"m_szLastPlaceName"`
	MThirdPersonViewAngles         uint `json:"m_thirdPersonViewAngles"`
	MVecOrigin                     uint `json:"m_vecOrigin"`
	MVecVelocity                   uint `json:"m_vecVelocity"`
	MVecViewOffset                 uint `json:"m_vecViewOffset"`
	MViewPunchAngle                uint `json:"m_viewPunchAngle"`
	MZoomLevel                     uint `json:"m_zoomLevel"`
}
